version: "3.7"
services:

  app:
      image: doodlelabsuk/lora-oil-app:v1
      container_name: lora-oil-app
      restart: unless-stopped
      volumes:
        - app-storage2:/var/www/storage
      networks:
        - lora-oil

# We don't need this for prod - use the host
#  db:
#    image: mariadb
#    container_name: lora-oil-db
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: oil_dev_db
#    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#    networks:
#      - lora-oil

  nginx:
    image: nginx:1.17-alpine
    container_name: lora-oil-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - lora-oil

networks:
  lora-oil:
    driver: bridge

volumes:
   app-storage2:
      name: app-storage2   
      external: true

